export { default as About } from './About'
export { default as Home } from './Home'
export { default as NotFound } from './NotFound'
export { default as Project } from './Project'
export { default as Projects } from './Projects'
